### ISSUE TITLE
Dark-mode?

### ISSUE THREAD

**Issue by rowild** [vue-final/vue-final-modal#153]
Is it possible to change background and text depending on a dark-mode class (on the body tag) or the `prefers-colo-scheme` media query?

Personally, I prefer to set a `dark-mode` class on the body tag. So I tried this in my CustomModal:

```css
::v-deep .dark-mode .modal-content {
  background: black;
  text: white;
}
```

But to no avail.
What would be the proper way to make that work?
