### ISSUE TITLE
Modal twitching on resize

### ISSUE THREAD

**Issue by wtcodeai** [vue-final/vue-final-modal#183]
### Version

vue-final-modal: v3.4.3
vue: v3.2.0 (3.2.20 in ex)

### OS

MacOS Monterey 12.0.1
Safari 15.1

### Reproduction Link
https://codesandbox.io/s/intelligent-franklin-piqt3

### Steps to reproduce
1. create template with HOC example and styles
2. Open modal
3. Try to resize

### What is Expected?
Modal resized in one direction

### What is actually happening?
Modal resizes and also changes position to opposite side

**Comment by hunterliu1003** [comment]
Hi @wtcodeai ,
Here is a temporary fix 
https://codesandbox.io/s/heuristic-curran-toxli?file=/src/components/SimpleModal.vue

I remove the `padding: 1rem` in class `.modal-content` and wrap one more `div`:
```html
<vue-final-modal
    content-class="modal-content"
>
    <div style="padding: 1rem">
       ...modal-content
    </div>
</vue-final-modal>
```

```css
.modal-content {
  position: relative;
  display: flex;
  flex-direction: column;
  max-height: 90%;
  margin: 0 1rem;
  /* padding: 1rem; */
  border: 1px solid #e2e8f0;
  border-radius: 0.25rem;
  background: #fff;
}
```
